### PR TITLE
chore(deps): Bump to Elysia 1.0.0

### PR DESCRIPTION
**Pull request by snorremd**
Elysia 1.0 introduces a breaking change for life cycle events.

> Starting from Elysia 1.0 RC, all lifecycle events including derive,
> and resolve will accept additional parameters
> { as: 'global' | 'local' } to specify if hook should be local or
> global which default to local

https://github.com/elysiajs/elysia/issues/513

elysia-htmx 1.0.9 does not specify such an option, and so any use of the plugin results in the `hx` property not being typed as available in the parent Elysia instance's handlers.

This commit updates dependencies to Elysia 1.0.10 and adds the as: "global" option to allow the hx parameter to be available in parent Elysia instances.

This mirrors how the official Bearer token plugin does it: https://github.com/elysiajs/elysia-bearer/blob/main/src/index.ts#L56

### CODE REVIEW

**Comment by snorremd** [comment]
I guess the plugin (peer) depending on a new major version of Elysia could be considered a breaking change in the plugin as well so if need be the version could be bumped to `2.0.0`. I'll leave that up to you.

**Comment by alexgorbatchev** [comment]
@gtramontina please merge and publish

**Comment by morigs** [comment]
looking forward for this update

**Comment by gtramontina** [comment]
Hey all, apologies for the long delay. Merging it now. Releasing a new version soon! 👍 
Thank you, @snorremd, for the contribution!

**Comment by gtramontina** [comment]
:tada: `2.0` released.

BTW, while this version will be available at `elysia-htmx`, going forward, new versions will be namespaced as `@gtramontina.com/elysia-htmx`, like https://github.com/gtramontina/elysia-tailwind

**Pull request merged**
